// <auto-generated />
using System;
using ITSOLUTION.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITSOLUTION.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260823022556_UpdateActivos_AddInventarioFields")]
    partial class UpdateActivos_AddInventarioFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITSOLUTION.Domain.Entities.ActivoIT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Almacenamiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoInventario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionMAC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("Especificaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemoriaRam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Procesador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoEquipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("SucursalId");

                    b.HasIndex("TenantId");

                    b.ToTable("Activos");
                });

            modelBuilder.Entity("ITSOLUTION.Domain.Entities.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorreoCorporativo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.HasIndex("TenantId");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("ITSOLUTION.Domain.Entities.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "TICKETS_READ",
                            Modulo = "Helpdesk",
                            Nombre = "Ver Tickets"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "TICKETS_CREATE",
                            Modulo = "Helpdesk",
                            Nombre = "Crear Tickets"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "TICKETS_RESOLVE",
                            Modulo = "Helpdesk",
                            Nombre = "Resolver Tickets"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "USERS_MANAGE",
                            Modulo = "Administración",
                            Nombre = "Gestionar Usuarios"
                        });
                });

            modelBuilder.Entity("ITSOLUTION.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Control total del sistema en la empresa",
                            Nombre = "Administrador TI",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Solo atiende incidencias de su sucursal",
                            Nombre = "Técnico Soporte",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("ITSOLUTION.Domain.Entities.RolPermiso", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("PermisoId")
                        .HasColumnType("int");

                    b.HasKey("RolId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("RolesPermisos");

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            PermisoId = 1
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 2
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 3
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 4
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 1
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 3
                        });
                });

            modelBuilder.Entity("ITSOLUTION.Domain.Entities.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Sucursales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "Av. Amazonas y Naciones Unidas",
                            EstaActiva = true,
                            Nombre = "TechCorp Matriz Quito",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 2,
                            Direccion = "Malecón 2000",
                            EstaActiva = true,
                            Nombre = "TechCorp Sucursal Guayaquil",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 3,
                            Direccion = "Centro Histórico",
                            EstaActiva = true,
                            Nombre = "GlobalNet Cuenca",
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("ITSOLUTION.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanSuscripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RUC_NIT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Estado = "Activo",
                            FechaCreacion = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            NombreComercial = "TechCorp S.A.",
                            PlanSuscripcion = "Premium",
                            RUC_NIT = "1790000000001",
                            RazonSocial = "Technology Corporation Ecuador S.A."
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Estado = "Activo",
                            FechaCreacion = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            NombreComercial = "GlobalNet",
                            PlanSuscripcion = "Standard",
                            RUC_NIT = "0990000000001",
                            RazonSocial = "Redes Globales del Ecuador Cia. Ltda."
                        });
                });

            modelBuilder.Entity("ITSOLUTION.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActividadesRealizadas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HoraAtencion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HoraCierre")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Solicita")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("ITSOLUTION.Domain.Entities.TicketAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketAttachments");
                });

            modelBuilder.Entity("ITSOLUTION.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.HasIndex("TenantId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Correo = "admin@techcorp.com",
                            EstaActivo = true,
                            NombreCompleto = "Admin TechCorp",
                            Password = "password123",
                            SucursalId = 1,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 2,
                            Correo = "juan@techcorp.com",
                            EstaActivo = true,
                            NombreCompleto = "Juan Soporte",
                            Password = "password123",
                            SucursalId = 1,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 3,
                            Correo = "maria@techcorp.com",
                            EstaActivo = true,
                            NombreCompleto = "María RH",
                            Password = "password123",
                            SucursalId = 1,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 4,
                            Correo = "carlos@globalnet.com",
                            EstaActivo = true,
                            NombreCompleto = "Carlos TI",
                            Password = "password123",
                            SucursalId = 3,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("ITSOLUTION.Domain.Entities.UsuarioRol", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("UsuariosRoles");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            RolId = 1
                        },
                        new
                        {
                            UsuarioId = 2,
                            RolId = 2
                        });
                });

            modelBuilder.Entity("ITSOLUTION.Domain.Entities.ActivoIT", b =>
                {
                    b.HasOne("ITSOLUTION.Domain.Entities.Empleado", "Empleado")
                        .WithMany("ActivosAsignados")
                        .HasForeignKey("EmpleadoId");

                    b.HasOne("ITSOLUTION.Domain.Entities.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITSOLUTION.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Sucursal");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ITSOLUTION.Domain.Entities.Empleado", b =>
                {
                    b.HasOne("ITSOLUTION.Domain.Entities.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITSOLUTION.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sucursal");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ITSOLUTION.Domain.Entities.RolPermiso", b =>
                {
                    b.HasOne("ITSOLUTION.Domain.Entities.Permiso", "Permiso")
                        .WithMany("RolesPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITSOLUTION.Domain.Entities.Rol", "Rol")
                        .WithMany("RolesPermisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ITSOLUTION.Domain.Entities.Sucursal", b =>
                {
                    b.HasOne("ITSOLUTION.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Sucursales")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ITSOLUTION.Domain.Entities.TicketAttachment", b =>
                {
                    b.HasOne("ITSOLUTION.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Attachments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ITSOLUTION.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("ITSOLUTION.Domain.Entities.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITSOLUTION.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sucursal");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ITSOLUTION.Domain.Entities.UsuarioRol", b =>
                {
                    b.HasOne("ITSOLUTION.Domain.Entities.Rol", "Rol")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITSOLUTION.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ITSOLUTION.Domain.Entities.Empleado", b =>
                {
                    b.Navigation("ActivosAsignados");
                });

            modelBuilder.Entity("ITSOLUTION.Domain.Entities.Permiso", b =>
                {
                    b.Navigation("RolesPermisos");
                });

            modelBuilder.Entity("ITSOLUTION.Domain.Entities.Rol", b =>
                {
                    b.Navigation("RolesPermisos");

                    b.Navigation("UsuariosRoles");
                });

            modelBuilder.Entity("ITSOLUTION.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Sucursales");
                });

            modelBuilder.Entity("ITSOLUTION.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("ITSOLUTION.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("UsuariosRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
